### ISSUE TITLE
Use variables from secrets.yml inside Capistrano deployment task

### ISSUE THREAD

**Issue by Startouf** [capistrano-plugins/capistrano-secrets-yml#3]
Suppose I have a webhook URL for a Slack channel in my secrets.yml, and I want to notify a slack channel once a deployment finished (so in a Capistrano after task) what should I do ? How do I read the secret from Capistrano ?

**Comment by NorseGaud** [comment]
I think this is a better question for capistrano project.

**Comment by Startouf** [comment]
Sorry, this post was made quite long ago.
Here is my solution for the record

Assuming you have an extra `deploy` key in your secrets file (same level as `development` or `production`)


```ruby
# config/deploy.rb
deploy_secrets = Capistrano::SecretsYml.local_secrets_yml('deploy')
if deploy_secrets
  activte_slack_with(slack_webhook: deploy_secrets['slack'])
else
  puts 'Missing :deploy key in secrets !'
end

namespace :notify do
  desc 'Notify Slack channel'
  task :slack do
    run_locally do
      slack_reviously_activated.ping('New deployment', channel: '#deploy')
    end
  end
end
```

**Comment by NorseGaud** [comment]
Thanks!
