### ISSUE TITLE
Error - please remove 'config secrets.yml' from git

### ISSUE THREAD

**Issue by Lubmes** [capistrano-plugins/capistrano-secrets-yml#4]
bundle exec cap production setup

I get

```
Error - please remove 'config/secrets.yml' from git:

    $ git rm --cached config/secrets.yml

and gitignore it:

    $ echo 'config/secrets.yml' >> .gitignore
```

I did `git rm --cached config/secrets.yml`. It says it's already gone, as it indeed is. 

All these things are taken care of. Are you still maintaining?

**Comment by NorseGaud** [comment]
@Lubmes I noticed that I got this initially too. 
Did you be sure to add exactly config/secrets.yml to the gitignore?

I think what solved it for me was to just completely delete the file, not just with the --cached flag and then do a push. Give that a shot and let me know if it still exists.
