### ISSUE TITLE
seems to be on wrong port since Net::SCP.upload!

### ISSUE THREAD

**Issue by ConfusedVorlon** [capistrano-plugins/capistrano-secrets-yml#7]
my setup works correctly up to commit 
https://github.com/capistrano-plugins/capistrano-secrets-yml/commit/56ced4f1dc5f4052dfd3a4f1eababcd1c447ff26 (Switched upload! to Net::SCP.upload! so we can use new...)

if I upgrade past this, then I get the following error

```
SSHKit::Runner::ExecuteError: Exception while executing as webuser@beta.nurtureit.io: Net::SSH::ConnectionTimeout
Caused by:
Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout
Caused by:
Errno::ETIMEDOUT: Operation timed out - connect(2) for 138.68.118.166:22
```

from the port, it looks like this is trying to connect on port 22 where it should be on port OTHER_PORT

I'm currently setting the port like so...

`server 'beta.nurtureit.io', user: 'webuser', roles: %w{app db web}, port: OTHER_PORT`

is there a different setting I should use, or is this a bug with secrets not using the port that other tasks use?

**Comment by NorseGaud** [comment]
Per https://github.com/capistrano-plugins/capistrano-secrets-yml/pull/8, fixed in 1.2.1

**Comment by ConfusedVorlon** [comment]
thank you

**Comment by NorseGaud** [comment]
Thanks for your patience.
